name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DockerImageName: grpc-chat-server:$(date +%s)

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build GrpcChatServer project
      run: dotnet build GrpcChatServer/GrpcChatServer.csproj
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DockerImageName
