name: .NET Core Desktop

on:
  push:
    tags:
      - '*'
    paths:
      - 'GrpcChat/**'
      - 'GrpcChatClient/**'
      - '.github/workflows/dotnet-desktop.yml'

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - run: dotnet build GrpcChatClient/GrpcChatClient.csproj
    
    - run: zip -r GrpcChatClient.zip GrpcChatClient/bin/Debug/net5.0-windows/*
        
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: GrpcChatClient.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GrpcChatClient
        path: GrpcChatClient/bin/Debug/net5.0-windows
    
